<a href="https://colab.research.google.com/github/AldoQueirozTinoco/Desafio-SeuBon-/blob/main/Desafio_SeuBon%C3%A9_Aldo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Desafio SeuBoné - Aldo Queiroz</h1>

##Sobre a análise:

A análise a seguir busca responder 3 perguntas:

1. Quais os top 3 produtos exportados por estado nos anos de 2020 e 2021?
2. Quais os top 3 produtos importados por estado nos anos de 2020 e 2021?
3. Quais os top 3 produtos exportados em cada mês de 2021 por estado?

##Importação das tabelas e formatação

  O primeiro passo para a análise será importar os frameworks para realizar as visualizações e operações nos dados, estarei utilizando o Python.

In [1]:
import pandas as pd
import numpy as np

Depois importamos as tabelas para o formato do Pandas por meio do link csv disponibilizado no site https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/estatisticas/base-de-dados-bruta em "Base de dados detalhada por NCM" para os anos de 2020 e 2021. Como são 4 tabelas, irei realizar uma análise na tabela de exportação de 2020 e depois automatizar o processo para as demais.

In [2]:
#Link dos arquivo csv transformado em variável para facilitar a leitura
csv2020Expo = "https://balanca.economia.gov.br/balanca/bd/comexstat-bd/ncm/EXP_2020.csv"

#Importação do arquivo CSV utilizando ; como separador, sem isso a tabela não é importada corretamente.
EXP_2020=pd.read_csv(csv2020Expo,sep=';')

Depois de importada a tabela, vamos para a formatação:

###Para os dados de 2020:

Vou começar com uma análise exploratória da tabela, verificar os tipos de seus atributos, quantas entradas têm no total, samples...

In [3]:
EXP_2020.head(10)

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2020,1,39211900,10,244,SP,4,817600,1,1,2
1,2020,3,48183000,10,573,SC,1,917800,1,1,69
2,2020,1,85364100,11,756,SP,1,817800,341,12,1668
3,2020,7,69109000,11,586,SP,7,147800,13,8,686
4,2020,6,87089990,10,97,SP,7,147600,5960,5960,49740
5,2020,12,64039990,13,611,CE,1,817800,816,624,21632
6,2020,4,20057000,10,301,ES,1,727600,9,9,32
7,2020,10,48025592,10,586,SC,7,917500,7241,7241,22886
8,2020,11,11022000,10,888,GO,1,917800,1074550,1074550,282729
9,2020,12,87088000,11,69,SP,1,817800,7501,260,6828

In [4]:
EXP_2020.sample(7)

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
789432,2020,11,85432000,11,845,SP,7,1017701,651,32,4238
447494,2020,3,21050010,10,467,SP,12,817800,34,34,105
224693,2020,8,84842000,10,275,SP,4,817700,1,1,134
519405,2020,10,85122011,11,399,SP,4,817700,10,40,1321
388389,2020,5,39262000,10,580,SP,12,817800,0,0,10
997449,2020,8,72107010,10,493,RS,4,817700,29,29,74
180901,2020,3,8044000,10,23,SP,4,817600,4080,4080,7838

 Vou trocar os nomes das colunas de acordo com "5. Tabelas de Correlações de Códigos e Classificações:" do site dos dados para nomes mais legíveis.

In [5]:
#Acessa as colunas diretamente e modifica.
#a quantidade de nomes deve ser exatamente a presente na tabela
EXP_2020.columns = ['Ano','Mês','Produto','Unidade','País','Estado','Transporte','Alfândega','Quantidade','Peso(Kg)','Valor']
EXP_2020

,Ano,Mês,Produto,Unidade,País,Estado,Transporte,Alfândega,Quantidade,Peso(Kg),Valor
0,2020,1,39211900,10,244,SP,4,817600,1,1,2
1,2020,3,48183000,10,573,SC,1,917800,1,1,69
2,2020,1,85364100,11,756,SP,1,817800,341,12,1668
3,2020,7,69109000,11,586,SP,7,147800,13,8,686
4,2020,6,87089990,10,97,SP,7,147600,5960,5960,49740
...,...,...,...,...,...,...,...,...,...,...,...
1344551,2020,8,85051990,10,169,RS,4,817700,0,0,4
1344552,2020,5,85444900,10,467,MA,1,317903,101,77,293
1344553,2020,2,84825090,11,845,SP,4,817700,100,8,690
1344554,2020,12,22021000,17,351,PR,1,927700,12,12,11
1344555,2020,3,85016400,11,386,SC,1,927700,1,76470,469563

Agora vamos verificar os tipos dos dados, se a tabela têm valores ausentes, os dados mais presentes na tabela e finalmente se há duplicatas.

In [6]:
EXP_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1344556 entries, 0 to 1344555
Data columns (total 11 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Ano         1344556 non-null  int64
 1   Mês         1344556 non-null  int64
 2   Produto     1344556 non-null  int64
 3   Unidade     1344556 non-null  int64
 4   País        1344556 non-null  int64
 5   Estado      1344556 non-null  object
 6   Transporte  1344556 non-null  int64
 7   Alfândega   1344556 non-null  int64
 8   Quantidade  1344556 non-null  int64
 9   Peso(Kg)    1344556 non-null  int64
 10  Valor       1344556 non-null  int64
dtypes: int64(10), object(1)
memory usage: 112.8+ MB

Verificando por valores ausentes

In [7]:
EXP_2020.isnull().sum()

Ano           0
Mês           0
Produto       0
Unidade       0
País          0
Estado        0
Transporte    0
Alfândega     0
Quantidade    0
Peso(Kg)      0
Valor         0
dtype: int64

Verificando dados mais presentes

In [8]:
#Faz um loop no qual para cada uma das colunas da tabela, verifica os primeiros valores mais presentes
for col in EXP_2020.columns:
    print(EXP_2020[col].value_counts(dropna=False).head(), '\n')

Ano
2020    1344556
Name: count, dtype: int64

Mês
12    127356
10    120243
11    119763
9     119085
8     118576
Name: count, dtype: int64

Produto
2071400     9020
39269090    6011
2023000     5723
40169300    5126
73181500    5095
Name: count, dtype: int64

Unidade
10    906363
11    349135
13     18943
17     18043
21     17576
Name: count, dtype: int64

País
63     83330
249    81340
586    78012
845    59170
158    55873
Name: count, dtype: int64

Estado
SP    561705
RS    167125
SC    133941
PR    123924
RJ     72686
Name: count, dtype: int64

Transporte
1     723045
4     353510
7     220043
12     26438
0      11912
Name: count, dtype: int64

Alfândega
817800     315034
817700     188613
817600     146224
917800      68949
1017700     65491
Name: count, dtype: int64

Quantidade
1     102238
0      70955
2      67407
3      40402
10     39405
Name: count, dtype: int64

Peso(Kg)
0    112511
1     78256
2     53499
3     36277
5     34392
Name: count, dtype: int64

Valor
6     8402
10    8327
8     8202
5     8169
4     8126
Name: count, dtype: int64

Agora irei checar por duplicatas

In [9]:
EXP_2020.duplicated().sum()

np.int64(0)

A tabela parece muito bem organizada, não aparenta ter valores ausentes/nulos e contêm a maioria de seus atributos com o tipo int. Agora farei o mesmo processo para as demais por meio de função.

In [10]:
#Exportando demais tabelas
csv2021Expo = "https://balanca.economia.gov.br/balanca/bd/comexstat-bd/ncm/EXP_2021.csv"

csv2020Imp = "https://balanca.economia.gov.br/balanca/bd/comexstat-bd/ncm/IMP_2020.csv"
csv2021Imp = "https://balanca.economia.gov.br/balanca/bd/comexstat-bd/ncm/IMP_2021.csv"

#Importação dos arquivo CSV utilizando ; como separador, sem isso a tabela não é importada corretamente.
EXP_2021=pd.read_csv(csv2021Expo,sep=';')
IMP_2020=pd.read_csv(csv2020Imp,sep=';')
IMP_2021=pd.read_csv(csv2021Imp,sep=';')

In [11]:
def relatorio_tabelas(df,name=''):
  print(f'Relatório da tabela {name}')
  print("-" * 40)
  print('Shape:',df.shape)
  if 'EXP' in name:
    df.columns = ['Ano','Mês','Produto','Unidade','País','Estado','Transporte','Alfândega','Quantidade','Peso(Kg)','Valor']
  else:
    df.columns=['Ano','Mês','Produto','Unidade','País','Estado','Transporte','Alfândega','Quantidade','Peso(Kg)','Valor','Frete','Seguro']
  print(df.info())
  print("Valores nulos:\n", df.isnull().sum())
  print("Duplicadas:", df.duplicated().sum())
  print("Anos únicos:", df['Ano'].unique())
  print("UFs únicas:", df['Estado'].unique())
  print()

relatorio_tabelas(EXP_2021,'EXP_2021')
relatorio_tabelas(IMP_2020,'IMP_2020')
relatorio_tabelas(IMP_2021,'IMP_2021')

Relatório da tabela EXP_2021
----------------------------------------
Shape: (1480295, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480295 entries, 0 to 1480294
Data columns (total 11 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Ano         1480295 non-null  int64
 1   Mês         1480295 non-null  int64
 2   Produto     1480295 non-null  int64
 3   Unidade     1480295 non-null  int64
 4   País        1480295 non-null  int64
 5   Estado      1480295 non-null  object
 6   Transporte  1480295 non-null  int64
 7   Alfândega   1480295 non-null  int64
 8   Quantidade  1480295 non-null  int64
 9   Peso(Kg)    1480295 non-null  int64
 10  Valor       1480295 non-null  int64
dtypes: int64(10), object(1)
memory usage: 124.2+ MB
None
Valores nulos:
 Ano           0
Mês           0
Produto       0
Unidade       0
País          0
Estado        0
Transporte    0
Alfândega     0
Quantidade    0
Peso(Kg)      0
Valor         0
dtype: int64
Duplicadas: 0
Anos únicos: [2021]
UFs únicas: ['SP' 'RS' 'MG' 'AL' 'SC' 'PR' 'GO' 'MT' 'ES' 'PA' 'MA' 'CE' 'RJ' 'BA'
 'AM' 'RO' 'AC' 'AP' 'MS' 'PI' 'PE' 'RR' 'DF' 'TO' 'RN' 'ND' 'SE' 'PB']

Relatório da tabela IMP_2020
----------------------------------------
Shape: (1784057, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1784057 entries, 0 to 1784056
Data columns (total 13 columns):
 #   Column      Dtype
---  ------      -----
 0   Ano         int64
 1   Mês         int64
 2   Produto     int64
 3   Unidade     int64
 4   País        int64
 5   Estado      object
 6   Transporte  int64
 7   Alfândega   int64
 8   Quantidade  int64
 9   Peso(Kg)    int64
 10  Valor       int64
 11  Frete       int64
 12  Seguro      int64
dtypes: int64(12), object(1)
memory usage: 176.9+ MB
None
Valores nulos:
 Ano           0
Mês           0
Produto       0
Unidade       0
País          0
Estado        0
Transporte    0
Alfândega     0
Quantidade    0
Peso(Kg)      0
Valor         0
Frete         0
Seguro        0
dtype: int64
Duplicadas: 0
Anos únicos: [2020]
UFs únicas: ['PR' 'ES' 'RS' 'SP' 'MG' 'CE' 'BA' 'PA' 'SC' 'MT' 'RJ' 'DF' 'AL' 'AM'
 'GO' 'MS' 'SE' 'PB' 'PE' 'RO' 'RN' 'AP' 'TO' 'MA' 'RR' 'PI' 'AC' 'ND'
 'EX']

Relatório da tabela IMP_2021
----------------------------------------
Shape: (1999946, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999946 entries, 0 to 1999945
Data columns (total 13 columns):
 #   Column      Dtype
---  ------      -----
 0   Ano         int64
 1   Mês         int64
 2   Produto     int64
 3   Unidade     int64
 4   País        int64
 5   Estado      object
 6   Transporte  int64
 7   Alfândega   int64
 8   Quantidade  int64
 9   Peso(Kg)    int64
 10  Valor       int64
 11  Frete       int64
 12  Seguro      int64
dtypes: int64(12), object(1)
memory usage: 198.4+ MB
None
Valores nulos:
 Ano           0
Mês           0
Produto       0
Unidade       0
País          0
Estado        0
Transporte    0
Alfândega     0
Quantidade    0
Peso(Kg)      0
Valor         0
Frete         0
Seguro        0
dtype: int64
Duplicadas: 0
Anos únicos: [2021]
UFs únicas: ['SP' 'PR' 'RS' 'RJ' 'AM' 'MG' 'GO' 'SC' 'MT' 'ES' 'PI' 'DF' 'BA' 'PE'
 'MS' 'RO' 'AL' 'CE' 'PB' 'SE' 'PA' 'RN' 'TO' 'EX' 'MA' 'RR' 'AP' 'AC']

Como fica evidente nas análises realizadas, todas as tabelas estão sem valores faltantes ou duplicatas e estão, ao todo, bem estruturadas. Logo, podemos prosseguir com a análise.